In [2]:
# INSTALLING NUMPY

!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
import numpy as np
numpy.__version__

'1.21.6'

In [10]:
# INITIALIZATION OF ARRAYS

# Array Initialization- Single Dimension

import numpy as np
a = np.array([7,9,9,21])
print(a)

[ 7  9  9 21]


In [14]:
# Array Initialization - Multi Dimension

import numpy as np
b = np.array([(7,9,9,2), (16,11,9,6),(2,5,6,9)])
print (b)

[[ 7  9  9  2]
 [16 11  9  6]
 [ 2  5  6  9]]


In [20]:
# Generating an Array

# range of values in array
c = np.arange(10)
# set of values by Interval [start,end,no.of valuesEqualInterval]
d = np.linspace(1,5,10)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [34]:
# PROPERTIES OF ARRAY

a = np.array([7,9,9,2])
b = np.array([(7,9,9,2), (16,11,9,6)])
print(b.ndim) #Dimension of Array
print(a.itemsize) #Byte Size of each Element
print(a.dtype) #Datatype of array
print(b.size*a.itemsize) #memory occupied - space occupied by 1 element * length of numyp array
print(b.size) #Number of elements of an array
print(b.shape) #Shape of array (rows and columns)

2
8
int64
64
8
(2, 4)


In [38]:
# ARRAY RESHAPE

b = np.array([(7,9,9,2), (16,11,9,6)])
print(b)
b = b.reshape(4,2)
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


In [43]:
# ARRAY SLICING

b = np.array([(7,9,9,2), (16,11,9,6)])
print(b[0,2]) #Slicing the Element from certain row and certain column b[row Index]
print
print(b[0:,2]) #Slicing Element from alll rows and cetain column

9
[9 9]


In [48]:
# ARRAY VALUE OPERATION

e = np.array([7,9,9,2, 16,11,9,6])
print(e.min())
print(e.max())
print(e.sum())

2
16
69


In [52]:
# ARITHMETIC OPERATION

a = np.array([7,9,9,2])
c = np.array([1,9,9,6])
print(a+c)
print(a-c)
print(a*c)
print(a/c)

[ 8 18 18  8]
[ 6  0  0 -4]
[ 7 81 81 12]
[7.         1.         1.         0.33333333]


In [61]:
a = np.array([7,9,9,2])
b = np.array([(7,9,9,2), (16,11,9,6)])
print(b.sum(axis=0)) #Each element of 1st dim array with same index with another dim element
print(b.sum(axis=1)) #Sum of all elements in 1st dim & sum of all element is 2nd dim
print(np.sqrt(a)) #Squaroot of array elements
print(np.std(a)) #Starndard deviation of array
print(np.exp(a)) # Exponential of array
print(np.log(a)) # Natural log - ln
print(np.log10(a)) #Log base 10


[23 20 18  8]
[27 42]
[2.64575131 3.         3.         1.41421356]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [69]:
b = np.array([(7,9,9,2), (16,11,9,6)])
f = np.array ([(1,2,3,4), (5,6,7,8)])
print(np.vstack((b,f))) #Vertical Stack
print(np.hstack((b,f))) #Horizontal Stack
print(b.ravel()) #Merge as single
print(f.ravel())

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
[ 7  9  9  2 16 11  9  6]
[1 2 3 4 5 6 7 8]


In [ ]:
# END